# Generated by Django 4.2 on 2023-04-10 16:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendslist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friends_List',
            new_name='FriendsList',
        ),
    ]
