# Generated by Django 4.2 on 2023-04-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gradelevels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('subject', models.CharField(max_length=255)),
                ('file', models.FileField(max_length=255, upload_to=None)),
                ('grade_level', models.ManyToManyField(to='gradelevels.gradelevel')),
            ],
        ),
    ]
