# Generated by Django 4.2 on 2023-04-17 15:30

import django.core.validators
from django.db import migrations, models
import resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=resources.models.upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx'])]),
        ),
    ]
