# Generated by Django 4.2 on 2023-04-18 15:00

from django.db import migrations, models
import resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_resource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=resources.models.upload_to),
        ),
    ]
